### ISSUE TITLE
Define standard: point-based features (e.g. traffic lights)

### ISSUE THREAD

**Issue by j-t-t** [Data4Democracy/crash-model#114]

**Comment by terryf82** [comment]
@j-t-t can this issue be considered closed now that https://github.com/Data4Democracy/crash-model/pull/151 has been merged in?

**Comment by j-t-t** [comment]
Working on some updates to the implementation - right now the new features aren't added to the model via the pipeline, and some other minor things, but the standard has been defined, so what we're doing in 1.2 is done, I think
