### ISSUE TITLE
Develop project FAQ

### ISSUE THREAD

**Issue by terryf82** [Data4Democracy/crash-model#119]

**Comment by terryf82** [comment]
We've had a couple of attempts at documenting this now, how about we try using an issue to manage it!

We already have an FAQ of sorts on the repo home page under "Project Overview" (https://github.com/Data4Democracy/boston-crash-modeling) and while it might look pretty bland, if we're looking for a single home for an FAQ it's probably the right place given how easily we can all update it.

It might be worth reorganizing that content to be a bit less "question & answer" e.g
"What is the goal of the project?" becomes "Project Goal"
"Who are the intended users of the project?" becomes "Intended Users"
etc...

and then we can setup a dedicated FAQ section below that. A couple of questions that I know have been asked a few times already are:

**Q. What is the current status of the project?**
We can just link to the latest release page (presently https://github.com/Data4Democracy/boston-crash-modeling/releases/tag/v1.1) which should always be written up with adequate notes about what the release is capable of)

**Q. How can I get involved in the project?**
Perhaps we should start tagging suitable issues as "newbie friendly" in the project boards? We can then link to a filter page for these, along with some organizational info (basically what's under "Connect" of the project page right now).

Thoughts / objections? I'm happy to take the lead on this one.

**Comment by csaidane** [comment]
Well, as a newbie, I can tell you the "newbie friendly" idea is a great one and it would definitely help people get set in. 
I think also that newbies might have a lot of technical questions that can be answered through internet research but that might discourage them from getting more involved in the project. For example, I think a couple lines explaining "What is docker and how do we use it" might be very useful (I know im personally trying to understand that very issue right now)

**Comment by shreyapandit** [comment]
Initial draft can be found here: https://docs.google.com/document/d/1k6sfCEPJHtFbufAJGJ_mFHzvs2Oktsea4eZWdBBXmjI/edit#

**Comment by bpben** [comment]
Addressed (at least preliminarily) with #303
