### ISSUE TITLE
Define standard: predictions

### ISSUE THREAD

**Issue by terryf82** [Data4Democracy/crash-model#122]

**Comment by terryf82** [comment]
Looking at defining a formal standard for our predictions output, in the same way we standardized crashes & concerns inputs.

Ideally our standard works for both file-based consumption by the viz (as it presently functions) and eventually api delivery from a db.

@bpben which is the file the predictions currently get output to?

**Comment by bpben** [comment]
seg_w_predicted.csv is output to the process folder at the moment.  Any changes to the format of the output would have to be run by @alicefeng as her viz scripts are the ones ingesting it.

**Comment by terryf82** [comment]
So it looks like there isn't too much data to deal with here at the moment, so the standard is appropriately brief:

https://github.com/Data4Democracy/crash-model/blob/data_standards/standards/predictions-schema.json
https://github.com/Data4Democracy/crash-model/blob/data_standards/standards/predictions-instance.json

The only noteworthy part at this stage is that the OSM segment ids look to allow for leading zeros, which means we need to use the JSON type string rather than number (which can't accommodate that) for the segment_ids.

@alicefeng how does this look from a visualization perspective, any concerns?

**Comment by alicefeng** [comment]
thanks for taking a first stab at this @terryf82 !  i have just one addition to request: could you also include the name of the city (and state/country) that the predictions are for?

the only other things to be aware of are that the temporal aspect (i.e., the week and year fields) might change since it sounds like @bpben has been playing around with that and also that we need to figure out a structure for sharing the explanatory features for each prediction which i think should be included as part of this data standard.

**Comment by terryf82** [comment]
Latest commit to data_standards branch has the temporal properties of each prediction made optional rather than required:

https://github.com/Data4Democracy/crash-model/blob/data_standards/standards/predictions-schema.json

@bpben how much work is involved in changing the predictions output from seg_w_predicted.csv into files that adhere to this schema? I'm happy to take a stab at it if you point me in the right direction, equally happy if you'd prefer to do it. Thanks.

**Comment by alicefeng** [comment]
Should we include the segment name and perhaps coordinates as part of the prediction standard?  Again, trying to think ahead to the future when we might have an API for this, how would users be able to translate our segment ids into something they understand and could place on a map?

**Comment by terryf82** [comment]
That sounds like a good idea - context of the prediction outside of our project.

We could either add properties that we think would be useful (name, co-ordinates etc.) or reference OSM entities (ways & nodes) that would include the same but from OSM. There's pros & cons to each approach, maybe a hybrid solution is best?

**Comment by alicefeng** [comment]
Yeah, maybe do both if that wouldn't be too difficult.

Also worth asking stakeholders what they would prefer I think - I'll add this to the list of questions for our presentation to Boston on the 25th.

**Comment by terryf82** [comment]
@alicefeng @bpben @j-t-t please check out the revised predictions schema & instance when you have a chance:

https://github.com/Data4Democracy/crash-model/blob/data_standards/standards/predictions-schema.json
https://github.com/Data4Democracy/crash-model/blob/data_standards/standards/predictions-instance.json

Essentially the segment has changed from just an id to a full object, to try and capture more of the relevant info. @alicefeng I'm not sure if the lat/lng setup works from your perspective, but rather than try and determine a centerpoint for a segment (which could be very long) I opted to include the lat/lng of OSM nodes used in the segment. But if a segment centerpoint is preferable (and achievable?) then I'm fine with us including that.

Thanks.

**Comment by alicefeng** [comment]
Looks great, thanks for updating @terryf82 !  A couple of thoughts:

The centerpoint is more to help me with some viz functionality - I felt it'd be nice if users could click on the name of a segment in our list of riskiest segments and have the map pan to that segment.  But the more I think about it, the more I feel this doesn't belong in the predictions standard.  I'll try to come up with a workaround for this myself.

But one thing that would be really nice (possibly critical) to include would be the linestring of the segment so users could replicate it on their own map.  At any rate, I need the linestring to be able to draw our predictions so it'd be immensely helpful if I didn't have to rejoin this data standard with inters_and_non_inters.json to get that information.

Finally, could we please add the name of the city that the segment and prediction is for?

**Comment by bpben** [comment]
I think the OSM info like lat long/linestring would have to be joined in any case because train_model doesn't pull in that information.  Would there be any issue with the prediction standard just being week, year, value along with features, which would take the form of list of key-value pairs?

**Comment by alicefeng** [comment]
Well the problem with it just being week, year, value and features is that a user wouldn't be able to locate that segment.  What does a segment ID of "0012345" mean?  Which [part of] a street does it refer to?  Unless we plan to provide some sort of separate endpoint/JSON that provides that lookup, I think omitting this kind of geographic info would render these predictions unusable.

I agree that adding things like segment names or OSM info doesn't have to happen in your train_model script but I don't think a prediction data point should be considered complete without including this information.

**Comment by bpben** [comment]
Segment id travels with the segment through the process, it should be
fairly simple to link it to any other information generated in the
process.  Or am I misunderstanding your question?

**Comment by j-t-t** [comment]
We can also use the ids that we're generating to link back to osm. I haven't implemented anything for intersection segments, but non-intersection segments are in the form <osm way id>-<from node id>-<to node id>

**Comment by alicefeng** [comment]
We need to iron out what we're linking these ids to if we aren't including this info in the standard.  I can say that, flat out, the viz cannot make use of these predictions without segment names and linestrings.  My first step would be to immediately join this data standard with something to get that info.  I would think that for many end users, they would need to do that as well.  So it'd be nice to just save everyone that step and include complete information in the standard.

**Comment by terryf82** [comment]
Closing this issue as discussed in the meeting - the draft standard is complete on the understanding that it will change to accommodate the output of the new pipeline step to merge predictions and segment data.
