### ISSUE TITLE
Show contributing factors of risk in a segment

### ISSUE THREAD

**Issue by terryf82** [Data4Democracy/crash-model#124]

**Comment by terryf82** [comment]
Similar to [Show a city's riskiest locations](https://github.com/Data4Democracy/boston-crash-modeling/issues/123) -

@alicefeng does @bpben need to supply additional data to make this achievable in the viz?

Worth creating a mockup so we can discuss how it might appear on screen?

**Comment by alicefeng** [comment]
This one's going to be fairly intertwined with #122 .  I have some ideas on how to visually present this info but I'm leaning toward introducing this in the next iteration of the viz which yes, I will make mock ups for so we can discuss.

**Comment by bpben** [comment]
@alicefeng did you mean  #123 ? I guess all three are pretty closely intertwined.  Yeah, @terryf82 , maybe it makes sense to outline this before we dig deep.  I think #123 and this one will have different visualizations, this one needs more digestion to be useful.

**Comment by alicefeng** [comment]
@bpben i thought that supplying the contributing factors would be a part of the predictions standard unless you're planning on outputting 2 files.

**Comment by bpben** [comment]
I guess I was thinking of them as separate.  But yeah, I guess since they'll be in one file it makes sense to have them be part of the same standard.

**Comment by bpben** [comment]
I think I clarified this in #248, what do you think @terryf82 and @alicefeng ? Closing, but feel free to reopen.
