### ISSUE TITLE
Segment + time-based model testing

### ISSUE THREAD

**Issue by terryf82** [Data4Democracy/crash-model#126]

**Comment by terryf82** [comment]
Definitely a lot to unpack in this one.

Let's start with what is the problem we're trying to solve. It seems like our current approach to generating predictions (per segment + week) doesn't align with what we think stakeholders might find most useful - if that's the case, what would be more useful? Do we need to seek additional input on this before making changes?

**Comment by bpben** [comment]
After testing, it seems like a segment-level model performs reasonably well, though it's difficult to compare with the week-level model as their outputs are pretty different.  With #154 I've added the ability to switch to a segment-level model with a config flag.  Kind of a stop-gap for now, we'll have to see which type of model works best in v2.  I think we can close this for now, testing, at least, is pretty much done.
