### ISSUE TITLE
Generate human-readable segment info

### ISSUE THREAD

**Issue by j-t-t** [Data4Democracy/crash-model#128]
For intersection segments, seems like it should be just X St & Y St
For non intersection segments, it could be the name of the road, but that's ambiguous. Should it be the name of the road and indicate that it's between these two intersections, or is there a better way

@alicefeng

**Comment by alicefeng** [comment]
Yeah X St & Y St for intersections seems good.  For intersections where more than 2 roads meet, would it just be X St, Y St & Z St?

For the non-intersection segments, "X St bet. Y St and Z St" as @j-t-t suggested in another issue is certainly descriptive though it could end up being kind of long.  Block numbers are another thought I had, ex, "2300 Block of X St"

Very open to other ideas.

**Comment by j-t-t** [comment]
When this is merged, I'll update the 'data-latest.zip'.

For this iteration, we're going to stick with the form "Cadbury Road" (without any more identifying detail) for non intersections. For intersection segments, most will look like "Geneva Street and Gove Street", but if there are a lot of different named segments coming in to the intersection, it'll be something like "Park Plaza near Columbus Avenue, Park Square and Eliot Street"
