### ISSUE TITLE
Handle military time, such as in Pittsburgh's case

### ISSUE THREAD

**Issue by j-t-t** [Data4Democracy/crash-model#180]

**Comment by mtjones330** [comment]
The time of day column for the Allegheny county crash data is represented as an integer in 24 hour format.

TIME_OF_DAY | HOUR_OF_DAY
-- | --
257 | 2
1027 | 10
1839 | 18
914 | 9
2230 | 22
1415 | 14
1430 | 14
847 | 8
1244 | 12
1150 | 11
1614 | 16
