### ISSUE TITLE
Allow point-based features to take values rather than just counts

### ISSUE THREAD

**Issue by j-t-t** [Data4Democracy/crash-model#194]
Currently, the point-based features functionality counts the number of features of a type on a particular segment, but we may want to take just a value (either most recent, or perhaps largest, or average? Depends on field type).

An example of where we might want to do this is in philly's volume data here: https://www.opendataphilly.org/dataset/dvrpc-traffic-counts/resource/13c61c65-8170-4bea-a219-a6ed172ba44f
Although Waze data might obviate the need for using this particular dataset, it's likely we might have other data sources that look similar, so I think this is a useful feature

Also this map is as a shapefile, rather than csv file, and we'd want to modify the data_standardization step to handle shapefiles (and update how we do the configuration file to handle these sorts of formats for point-based data).

**Comment by christophercahill** [comment]
Hi, I'm not sure how to assign myself, but I am starting work on this!

**Comment by terryf82** [comment]
Hey Chris, have you accepted the invitation to join yet?

I just tried but still can't assign you, the invite may be the reason.

**Comment by christophercahill** [comment]
I just accepted the invite and assigned myself.
