### ISSUE TITLE
Resolve GitLFS breakages

### ISSUE THREAD

**Issue by terryf82** [Data4Democracy/crash-model#209]

**Comment by terryf82** [comment]
@j-t-t @shreyapandit @alicefeng 

The symptom of this problem is that git reports the city-specific archives in data_zips have changed when trying to swap between branches, even though no changes have happened in those files.

This [thread](https://github.com/git-lfs/git-lfs/issues/1465) is a couple of years old now, but it seems to pretty closely describe the issues we're having. Suggested remediation when you hit this issue is:

1. [Confirm](https://github.com/git-lfs/git-lfs/issues/1465#issuecomment-240799330) both branches recognise the files as being LFS using `git ls-tree`

2. [Diff](https://github.com/git-lfs/git-lfs/issues/1465#issuecomment-240813252) the files to see if they're recognised as binary.

3. If they are binary, (run git lfs install)[https://github.com/git-lfs/git-lfs/issues/1465#issuecomment-240825204] (which looks to be different to actually "installing" git lfs, I'm pretty sure I fell into this trap on my work computer). (Confirm)[https://github.com/git-lfs/git-lfs/issues/1465#issuecomment-240828838] it's installed by checking the git config as described.

If you get through all that and are still experiencing issues let me know. Thanks.

**Comment by terryf82** [comment]
It's possible that we may need to resort to using [git lfs migrate](https://github.com/git-lfs/git-lfs/issues/1939#issuecomment-353247795) to fix commits that have already been pushed, but I'd like to hear if the above ideas help others first (they haven't worked fully for me).

**Comment by j-t-t** [comment]
Following those steps enables me to switch branches without encountering the error I had before. However, it still shows that I have modified those files (regardless of what branch I'm on), and when I try to do a git checkout on them, I get `Encountered 3 file(s) that should have been pointers, but weren't`, which is a message I have seen before...

**Comment by terryf82** [comment]
I can't say for certain but it sounds like at some point the zips have been committed without LFS being used. The way to fix this looks to be using the migrate subcommand I linked to above, here's the gist of it:

> git lfs migrate import will repair your repository by migrating any blobs that should be stored with LFS to be so. You can push this to a remote via git push --all origin, or git push --all --force origin if you migrated commits that are already present on the remote.

Force push has always made me a little nervous, but I expect it's what we need to do in this case. Unless we decide now that git LFS isn't working for this project and we want to look at other options. What do you think @j-t-t ?

**Comment by terryf82** [comment]
Files managed by GitLFS have been removed from the repo and will no longer be used to manage data, for now we're reverting to using data.world.

@j-t-t @bpben @alicefeng
