### ISSUE TITLE
Create prediction dashboard

### ISSUE THREAD

**Issue by therriault** [Data4Democracy/crash-model#21]
Potential enhancement: given a set of predictions, show a dashboard that describe the predictions and provide useful information (as a complement to a map of predictions). For example:

- What are the top 5 or 10 most dangerous street segments?
- How many predictions are above a given threshold?
- How has the average risk level across all segments changed over time?

**Comment by bpben** [comment]
Kind of covered and distributed across some other issues right now.  Closing.
