### ISSUE TITLE
Viz upgrade - show crash dates and increase contrast

### ISSUE THREAD

**Issue by terryf82** [Data4Democracy/crash-model#215]
We should have the data to support showing crash dates in the dialog window that appears when you click on a crash circle.

Right now it shows e.g

"x crashes"

but this could be extended to:

"x crashes:
- date/time of first crash
- date/time of second crash
etc..."

Also we discussed the idea of reverting to the purple crash circles, to improve their contrast against the map.

**Comment by alicefeng** [comment]
What's the point of showing the crash dates and times now that the model doesn't have a temporal aspect anymore?  Maybe it makes more sense to show the lat/long coordinates so the user can look up when crashes happened in the crash dataset they're supplying.

**Comment by j-t-t** [comment]
I'd still like to see the dates, if it's possible to do. I envision this as a tool that advocacy groups can use also, and if they want to easily see when crashes happened in a certain area (which was actually a request our local bike advocacy group made of me), it would be great if there's a tool they can use without having to dig into the data themselves.

**Comment by alicefeng** [comment]
So are we envisioning there will be people who will use the viz but not run the pipeline themselves?

**Comment by alicefeng** [comment]
Closed by #229
