### ISSUE TITLE
Update misleading documentation wording

### ISSUE THREAD

**Issue by delewis13** [Data4Democracy/crash-model#221]
Under the "How does the project achieve its goal?" header:

"Predictions are generated on a per road-segment basis and will be made available via a searchable web visualization, with roads of highest risk easily identifiable. **Details of which factors are most associated with risk on each road will also be included**."

As far as I can tell, these factors are output by model.features_importances_ [for XGboost at least]. This gives feature importance for the data-set as a whole, rather than showing the feature weightings / contributions for a single road segment.

Should perhaps instead read "**Details of which factors are most associated with risk for the dataset as a whole will also be included**".

Cheers :)

**Comment by bpben** [comment]
Whoa, really delayed response on this, sorry.  But you're right.  We're actually working on explanatory features in #103 so until that's locked down we probably will leave as is.  Thanks for the comment, though!
