### ISSUE TITLE
Access to the data and contributing

### ISSUE THREAD

**Issue by lemartinet** [Data4Democracy/crash-model#233]
Hi,
I'm working on a data science project and I'm investigating the effect of adding bike lane on the bike crash rate. I've downloaded open data from the BARI for 2009-2012 and from Vision Zero for 2015-2018. But from looking at your project here, it seems that you have data for the 2012-2014 period too. If so, would it be possible to use it? And subsequently, I'd be interested in sharing with you guys the outcome of my project and getting some feedback!
I've tried to contact you through the D4D website too.
Thanks!

**Comment by j-t-t** [comment]
Hi,

Welcome! The best way to get connected is through slack - did you try emailing team [at] datafordemocracy.org to ask to get added to the slack? My understanding is that's the current mechanism, but if it isn't, we can figure out who can add you.

It sounds like a great project. Currently, we're using open street maps maps, which get us some bike lane information, and there are other ways we can import city-specific data. I'm not sure what BARI is, so I don't know which city you're in. We have different years for different cities. Anyway, welcome, and once you're on slack (our channel is p-boston-crash-model), it'll be easier to continue the conversation.

**Comment by lemartinet** [comment]
Thanks for your reply! I tried to contact D4D through the form on the
website. I'll try to email them again to gain access to the slack.
I'm based in Boston, and sorry for the jargon, BARI is the Boston Area
Research Initiative and they released some data in the past for bike
accidents.

**Comment by lemartinet** [comment]
Hey! I still haven't heard back from D4D after sending an email. Should I wait a bit longer or try a different approach?
Thanks!

**Comment by j-t-t** [comment]
I will see if I can figure out how to get you added.

**Comment by j-t-t** [comment]
You should receive an invite on the email associated with your github account today (if you don't, or if that's not the email you want to use, let us know)
