### ISSUE TITLE
too many files and i dont know how to start

### ISSUE THREAD

**Issue by marammuabrak** [Data4Democracy/crash-model#239]
hello 
i saw your work and its amazing and i want to try it but there is too many files and i dont know where to start can you help me

**Comment by j-t-t** [comment]
Hi,

Welcome! The best way to get started is to get a Data for Democracy slack account, join our channel, and introduce yourself there. You can submit your information here: https://www.datafordemocracy.org/join-us. If after a couple of days, you don't hear back after submitting, you can give us your email address and we see if we can get you added to slack directly.

Jenny

**Comment by marammuabrak** [comment]
hello m i joined but still don't receive any email 
My email "MaramMubarak@hotmail.com

thank you

**Comment by j-t-t** [comment]
We sent an invite for the slack channel a couple of days ago - if you didn't get it, please let us know.
Once you have a slack account, join the #p-boston-crash-model channel and say hello

**Comment by bpben** [comment]
Hey @marammuabrak glad you're interested! There's readme files with background and instructions in the [main page](https://github.com/Data4Democracy/crash-model) and in [src](https://github.com/Data4Democracy/crash-model/tree/master/src).  Check those out and let us know if you have issues.  Closing this now, as we'll discuss in slack.
