### ISSUE TITLE
make_canon_dataset needs a check for segment/week level

### ISSUE THREAD

**Issue by bpben** [Data4Democracy/crash-model#241]
Right now the only place that the yaml config file is checked for whether prediction should be at the segment or week level is in train_model.  Right now the make_canon_dataset always groups by date, which will break it if the date field is not properly formatted.  I think we need to add a check into make_canon_dataset.

@j-t-t , thoughts?

**Comment by j-t-t** [comment]
Will be removing week level option

**Comment by bpben** [comment]
Should we move this to a new issue? Looks like the deprecate week-level should be its own thing, since it also means we need to change config defaults and remove from train_model.

**Comment by j-t-t** [comment]
Good point, I filed a new task for that, and closing this one.
