### ISSUE TITLE
Link bike lanes / routes to segments

### ISSUE THREAD

**Issue by therriault** [Data4Democracy/crash-model#26]
Geospatial data on the City's network of bike lanes / routes:

https://data.boston.gov/dataset/existing-bike-network ([Data Dictionary](https://github.com/Data4Democracy/boston-crash-modeling/files/1346636/Boston_Bike_Network_Data_Dictionary_August_2016.xlsx))

Should be pretty easy to import with a segment mapping because it uses the MassDOT road inventory that the segments are built from. One important detail: the install year should be included in the mapping, so that we don't include bike lanes installed after a given crash incident (which may be endogenous!). So I'd suggest the output dataset format (columns) be something like:

-segment ID
-year (only include bike lanes installed _before_ that year - this should be the year of the outcome data on crashes that are being mapped to these features, so basically think of this as "as of January 1, 20XX...")
-segment-specific characteristics (though these aren't exactly time-invariant, our crash training data is recent enough that we can treat them as if they are, so we'd repeat these for each year)

Note that the dataset has a bunch of other characteristics about roadway features (width, lanes, whether's it a key MBTA bus route, etc.) that would also be useful for including as features.

**Comment by bpben** [comment]
Removing help wanted from this, as it is dependent on our outcome, we're not currently looking at specifically bike accidents and I have trouble seeing the value of it as a feature otherwise.

**Comment by j-t-t** [comment]
Added open street map bike lanes to the model
