### ISSUE TITLE
Give appropriate mph/kph on slider

### ISSUE THREAD

**Issue by j-t-t** [Data4Democracy/crash-model#275]
Looks like it's kph for all cities now

**Comment by alicefeng** [comment]
Yep, I realized this too as I was working on polishing things up for Brisbane. We're going to need to somehow tell the viz whether a city is using metric or imperial units for its speed.

**Comment by j-t-t** [comment]
Sounds like a job for the config file :)

**Comment by alicefeng** [comment]
I think so too!
